# Generated by Django 4.1.5 on 2023-01-21 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='desc',
            new_name='pdesc',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='img',
            new_name='pimg',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='pname',
        ),
    ]
